version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./utf8_set:/etc/mysql/conf.d
volumes:
  mariadb-data: