version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./settings/secrets/initial.env
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./settings/conf:/etc/mysql/conf.d
volumes:
  mariadb-data: